name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libudev-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libegl1-mesa-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libwayland-dev \
          libxkbcommon-dev
    - name: Build
      run: cargo build --verbose
    - name: Setup DB
      run: |
        sudo apt-get install -y postgresql-client
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f tests/structure.sql
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f tests/seed.sql

    - name: Run tests
      run: cargo test --verbose
